# JAX Quickstart

[![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/google/jax/blob/main/docs/notebooks/quickstart.ipynb)

**JAX is NumPy on the CPU, GPU, and TPU, with great automatic differentiation for high-performance machine learning research.**

With its updated version of [Autograd](https://github.com/hips/autograd), JAX
can automatically differentiate native Python and NumPy code. It can
differentiate through a large subset of Python’s features, including loops, ifs,
recursion, and closures, and it can even take derivatives of derivatives of
derivatives. It supports reverse-mode as well as forward-mode differentiation, and the two can be composed arbitrarily
to any order.

What’s new is that JAX uses
[XLA](https://www.tensorflow.org/xla)
to compile and run your NumPy code on accelerators, like GPUs and TPUs.
Compilation happens under the hood by default, with library calls getting
just-in-time compiled and executed. But JAX even lets you just-in-time compile
your own Python functions into XLA-optimized kernels using a one-function API.
Compilation and automatic differentiation can be composed arbitrarily, so you
can express sophisticated algorithms and get maximal performance without having
to leave Python.

In [1]:
import jax.numpy as jnp
from jax import grad, jit, vmap
from jax import random

In [2]:
# Prevent GPU/TPU warning.
import jax
# jax.config.update('jax_platform_name', 'cpu')

In [4]:
jax.config.values

{'experimental_cpp_jit': True,
 'experimental_cpp_pmap': False,
 'experimental_xmap_ensure_fixed_sharding': False,
 'experimental_xmap_spmd_lowering': False,
 'jax_backend_target': '',
 'jax_check_tracer_leaks': False,
 'jax_debug_infs': False,
 'jax_debug_nans': False,
 'jax_default_matmul_precision': None,
 'jax_default_prng_impl': 'threefry2x32',
 'jax_disable_jit': False,
 'jax_disable_most_optimizations': False,
 'jax_distributed_debug': False,
 'jax_enable_checks': False,
 'jax_enable_custom_prng': False,
 'jax_enable_x64': False,
 'jax_hlo_source_file_canonicalization_regex': None,
 'jax_host_callback_inline': False,
 'jax_host_callback_max_queue_byte_size': 256000000,
 'jax_host_callback_outfeed': False,
 'jax_log_compiles': False,
 'jax_numpy_rank_promotion': 'allow',
 'jax_omnistaging': True,
 'jax_platform_name': '',
 'jax_platforms': '',
 'jax_traceback_filtering': 'auto',
 'jax_tracer_error_num_traceback_frames': 5,
 'jax_xla_backend': ''}

## Multiplying Matrices

We'll be generating random data in the following examples. One big difference between NumPy and JAX is how you generate random numbers. For more details, see [Common Gotchas in JAX].

[Common Gotchas in JAX]: https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#%F0%9F%94%AA-Random-Numbers

In [4]:
key = random.PRNGKey(0)
x = random.normal(key, (20,))
print(x)

[ 1.054516   -0.9692889  -0.59460217 -0.0318858   2.410932   -1.8784496
 -0.7847697  -0.3137085   0.33370885  1.767703   -1.0277647   1.4111717
 -0.5084972  -0.5263776   0.5031503   1.0549793  -0.0874074   0.79581654
  2.656559   -0.5822907 ]


Let's dive right in and multiply two big matrices.

In [8]:
size = 3000
x = random.normal(key, (size, size), dtype=jnp.float32)
%timeit jnp.dot(x, x.T).block_until_ready()  # runs on the GPU

1 loop, best of 5: 856 ms per loop


We added that `block_until_ready` because JAX uses asynchronous execution by default (see {ref}`async-dispatch`).

JAX NumPy functions work on regular NumPy arrays.

In [6]:
import numpy as np
x = np.random.normal(size=(size, size)).astype(np.float32)
%timeit jnp.dot(x, x.T).block_until_ready()

1 loop, best of 5: 849 ms per loop


That's slower because it has to transfer data to the GPU every time. You can ensure that an NDArray is backed by device memory using {func}`~jax.device_put`.

In [7]:
from jax import device_put

x = np.random.normal(size=(size, size)).astype(np.float32)
x = device_put(x)
%timeit jnp.dot(x, x.T).block_until_ready()

1 loop, best of 5: 915 ms per loop


The output of {func}`~jax.device_put` still acts like an NDArray, but it only copies values back to the CPU when they're needed for printing, plotting, saving to disk, branching, etc. The behavior of {func}`~jax.device_put` is equivalent to the function `jit(lambda x: x)`, but it's faster.

If you have a GPU (or TPU!) these calls run on the accelerator and have the potential to be much faster than on CPU.
See {ref}`faq-jax-vs-numpy` for more comparison of performance characteristics of NumPy and JAX

JAX is much more than just a GPU-backed NumPy. It also comes with a few program transformations that are useful when writing numerical code. For now, there are three main ones:

 - {func}`~jax.jit`, for speeding up your code
 - {func}`~jax.grad`, for taking derivatives
 - {func}`~jax.vmap`, for automatic vectorization or batching.

Let's go over these, one-by-one. We'll also end up composing these in interesting ways.

## Using {func}`~jax.jit` to speed up functions

JAX runs transparently on the GPU (or CPU, if you don't have one, and TPU coming soon!). However, in the above example, JAX is dispatching kernels to the GPU one operation at a time. If we have a sequence of operations, we can use the `@jit` decorator to compile multiple operations together using [XLA](https://www.tensorflow.org/xla). Let's try that.

In [10]:
def selu(x, alpha=1.67, lmbda=1.05):
  return lmbda * jnp.where(x > 0, x, alpha * jnp.exp(x) - alpha)

x = random.normal(key, (1000000,))
%timeit selu(x).block_until_ready()

100 loops, best of 5: 4.39 ms per loop


We can speed it up with `@jit`, which will jit-compile the first time `selu` is called and will be cached thereafter.

In [12]:
selu_jit = jit(selu)
%timeit selu_jit(x).block_until_ready()

1000 loops, best of 5: 1.31 ms per loop


## Taking derivatives with {func}`~jax.grad`

In addition to evaluating numerical functions, we also want to transform them. One transformation is [automatic differentiation](https://en.wikipedia.org/wiki/Automatic_differentiation). In JAX, just like in [Autograd](https://github.com/HIPS/autograd), you can compute gradients with the {func}`~jax.grad` function.

In [13]:
def sum_logistic(x):
  return jnp.sum(1.0 / (1.0 + jnp.exp(-x)))

x_small = jnp.arange(3.)
derivative_fn = grad(sum_logistic)
print(derivative_fn(x_small))

[0.25       0.19661197 0.10499357]


In [21]:
sum_logistic(x_small)

DeviceArray(2.1118555, dtype=float32)

In [22]:
derivative_fn(x_small)

DeviceArray([0.25      , 0.19661197, 0.10499357], dtype=float32)

Let's verify with finite differences that our result is correct.

In [14]:
def first_finite_differences(f, x):
  eps = 1e-3
  return jnp.array([(f(x + eps * v) - f(x - eps * v)) / (2 * eps)
                   for v in jnp.eye(len(x))])


print(first_finite_differences(sum_logistic, x_small))

[0.24998187 0.1964569  0.10502338]


Taking derivatives is as easy as calling {func}`~jax.grad`. {func}`~jax.grad` and {func}`~jax.jit` compose and can be mixed arbitrarily. In the above example we jitted `sum_logistic` and then took its derivative. We can go further:

In [23]:
print(grad(jit(grad(jit(grad(sum_logistic)))))(1.0))

-0.035325598


For more advanced autodiff, you can use {func}`jax.vjp` for reverse-mode vector-Jacobian products and {func}`jax.jvp` for forward-mode Jacobian-vector products. The two can be composed arbitrarily with one another, and with other JAX transformations. Here's one way to compose them to make a function that efficiently computes full Hessian matrices:

In [24]:
from jax import jacfwd, jacrev
def hessian(fun):
  return jit(jacfwd(jacrev(fun)))

## Auto-vectorization with {func}`~jax.vmap`

JAX has one more transformation in its API that you might find useful: {func}`~jax.vmap`, the vectorizing map. It has the familiar semantics of mapping a function along array axes, but instead of keeping the loop on the outside, it pushes the loop down into a function’s primitive operations for better performance. When composed with {func}`~jax.jit`, it can be just as fast as adding the batch dimensions by hand.

We're going to work with a simple example, and promote matrix-vector products into matrix-matrix products using {func}`~jax.vmap`. Although this is easy to do by hand in this specific case, the same technique can apply to more complicated functions.

In [ ]:
mat = random.normal(key, (150, 100))
batched_x = random.normal(key, (10, 100))

def apply_matrix(v):
  return jnp.dot(mat, v)

Given a function such as `apply_matrix`, we can loop over a batch dimension in Python, but usually the performance of doing so is poor.

In [ ]:
def naively_batched_apply_matrix(v_batched):
  return jnp.stack([apply_matrix(v) for v in v_batched])

print('Naively batched')
%timeit naively_batched_apply_matrix(batched_x).block_until_ready()

We know how to batch this operation manually. In this case, `jnp.dot` handles extra batch dimensions transparently.

In [ ]:
@jit
def batched_apply_matrix(v_batched):
  return jnp.dot(v_batched, mat.T)

print('Manually batched')
%timeit batched_apply_matrix(batched_x).block_until_ready()

However, suppose we had a more complicated function without batching support. We can use {func}`~jax.vmap` to add batching support automatically.

In [ ]:
@jit
def vmap_batched_apply_matrix(v_batched):
  return vmap(apply_matrix)(v_batched)

print('Auto-vectorized with vmap')
%timeit vmap_batched_apply_matrix(batched_x).block_until_ready()

Of course, {func}`~jax.vmap` can be arbitrarily composed with {func}`~jax.jit`, {func}`~jax.grad`, and any other JAX transformation.

This is just a taste of what JAX can do. We're really excited to see what you do with it!